when:
  - event: pull_request
  - event: push
    branch: main

steps:
  - name: go-test
    image: dhi.io/golang:1.26.4-debian13-dev@sha256:9350c6e0c0a06f23b487c39850188b2a5c2bd176d1fc5ae361400c8c068e42b0
    environment:
      DHI_USERNAME:
        from_secret: dhi_username
      DHI_PASSWORD:
        from_secret: dhi_password
    commands:
      - go test ./...
      - go vet ./...
      - test -z "$(gofmt -l .)"
